#  !import pprint;pprint.pprint(CONF._namespace.__dict__)
a= {'_conf': <oslo_config.cfg.ConfigOpts object at 0x7fdc64d69b10>,
 '_config_dirs': [],
 '_emitted_deprecations': set(),
 '_files_not_found': [],
 '_files_permission_denied': [],
 '_normalized': [{'DEFAULT': {'auth_strategy': ['keystone'],
                              'backup_ceph_chunk_size': ['1048576'],
                              'backup_ceph_conf': ['/etc/ceph/ceph.conf'],
                              'backup_ceph_pool': ['backups'],
                              'backup_ceph_stripe_count': ['0'],
                              'backup_ceph_stripe_unit': ['0'],
                              'backup_ceph_user': ['backup'],
                              'control_exchange': ['cinder'],
                              'debug': ['false'],
                              'default_volume_type': ['normal'],
                              'enable_force_upload': ['true'],
                              'enable_v1_api': ['false'],
                              'enabled_backends': ['normal'],
                              'get_rados_info_user': ['openstack'],
                              'glance_api_version': ['2'],
                              'glance_host': ['192.168.41.10'],
                              'log_dir': ['/var/log/cinder'],
                              'my_ip': ['192.168.41.1'],
                              'no_snapshot_gb_quota': ['true'],
                              'notification_driver': ['messagingv2'],
                              'nova_catalog_admin_info': ['compute:Compute Service:adminURL'],
                              'nova_catalog_info': ['compute:Compute Service:publicURL'],
                              'nova_endpoint_admin_template': ['http://192.168.41.10:8774/v2/%(project_id)s'],
                              'nova_endpoint_template': ['http://192.168.41.10:8774/v2/%(project_id)s'],
                              'os_region_name': ['RegionOne'],
                              'osapi_volume_listen': ['192.168.41.1'],
                              'osapi_volume_workers': ['12'],
                              'quota_backup_gigabytes': ['-1'],
                              'quota_backups': ['-1'],
                              'quota_snapshots': ['-1'],
                              'rpc_response_timeout': ['60'],
                              'storage_availability_zone': ['zettakit'],
                              'use_stderr': ['false'],
                              'verbose': ['true'],
                              'volume_clear': ['none'],
                              'volume_driver': ['cinder.volume.drivers.rbd.RBDDriver'],
                              'volume_service_inithost_offload': ['true']},
                  'database': {'connection': ['mysql+pymysql://cinder:cinder_dbpass@192.168.41.10/cinder'],
                               'db_max_retries': ['-1'],
                               'db_max_retry_interval': ['1'],
                               'max_retries': ['-1'],
                               'retry_interval': ['1'],
                               'use_db_reconnect': ['true']},
                  'keystone_authtoken': {'auth_type': ['password'],
                                         'auth_uri': ['http://192.168.41.10:5000'],
                                         'auth_url': ['http://192.168.41.10:35357'],
                                         'auth_version': ['v3'],
                                         'password': ['cinder'],
                                         'project_domain_name': ['default'],
                                         'project_name': ['service'],
                                         'region_name': ['RegionOne'],
                                         'user_domain_name': ['default'],
                                         'username': ['cinder']},
                  'normal': {'max_over_subscription_ratio': ['10'],
                             'rados_connect_timeout': ['5'],
                             'rados_connection_interval': ['5'],
                             'rados_connection_retries': ['3'],
                             'rbd_ceph_conf': ['/etc/ceph/ceph.conf'],
                             'rbd_cluster_name': ['ceph'],
                             'rbd_exclusive_cinder_pool': ['false'],
                             'rbd_flatten_volume_from_snapshot': ['false'],
                             'rbd_max_clone_depth': ['5'],
                             'rbd_pool': ['volumes'],
                             'rbd_secret_uuid': ['7e0fb456-26bd-4b14-b039-2b986fdcbcc4'],
                             'rbd_store_chunk_size': ['4'],
                             'rbd_user': ['openstack'],
                             'volume_backend_name': ['normal'],
                             'volume_driver': ['cinder.volume.drivers.rbd.RBDDriver']},
                  'oslo_concurrency': {'lock_path': ['$state_path/tmp']},
                  'oslo_messaging_rabbit': {'amqp_durable_queues': ['false'],
                                            'heartbeat_rate': ['2'],
                                            'heartbeat_timeout_threshold': ['30'],
                                            'kombu_failover_strategy': ['round-robin'],
                                            'rabbit_ha_queues': ['true'],
                                            'rabbit_hosts': ['192.168.41.1:5672, 192.168.41.2:5672, 192.168.41.3:5672'],
                                            'rabbit_max_retries': ['0'],
                                            'rabbit_password': ['openstack'],
                                            'rabbit_retry_backoff': ['2'],
                                            'rabbit_retry_interval': ['1'],
                                            'rabbit_userid': ['openstack']},
                  'resource': {'auth_uri': ['http://192.168.41.10:5000/v3'],
                               'password': ['cinder'],
                               'project_domain_name': ['default'],
                               'project_name': ['service'],
                               'user_domain_name': ['default'],
                               'username': ['cinder']}},
                 {'DEFAULT': {'auth_strategy': ['keystone'],
                              'iscsi_helper': ['lioadm'],
                              'lock_path': ['/var/lib/cinder/tmp'],
                              'logdir': ['/var/log/cinder'],
                              'rootwrap_config': ['/etc/cinder/rootwrap.conf'],
                              'state_path': ['/var/lib/cinder'],
                              'volumes_dir': ['/etc/cinder/volumes']},
                  'database': {'connection': ['mysql://cinder:cinder@localhost/cinder']},
                  'keystone_authtoken': {'auth_host': ['127.0.0.1'],
                                         'auth_port': ['35357'],
                                         'auth_protocol': ['http']}}],
 '_parsed': [{'DEFAULT': {'auth_strategy': ['keystone'],
                          'backup_ceph_chunk_size': ['1048576'],
                          'backup_ceph_conf': ['/etc/ceph/ceph.conf'],
                          'backup_ceph_pool': ['backups'],
                          'backup_ceph_stripe_count': ['0'],
                          'backup_ceph_stripe_unit': ['0'],
                          'backup_ceph_user': ['backup'],
                          'control_exchange': ['cinder'],
                          'debug': ['false'],
                          'default_volume_type': ['normal'],
                          'enable_force_upload': ['true'],
                          'enable_v1_api': ['false'],
                          'enabled_backends': ['normal'],
                          'get_rados_info_user': ['openstack'],
                          'glance_api_version': ['2'],
                          'glance_host': ['192.168.41.10'],
                          'log_dir': ['/var/log/cinder'],
                          'my_ip': ['192.168.41.1'],
                          'no_snapshot_gb_quota': ['true'],
                          'notification_driver': ['messagingv2'],
                          'nova_catalog_admin_info': ['compute:Compute Service:adminURL'],
                          'nova_catalog_info': ['compute:Compute Service:publicURL'],
                          'nova_endpoint_admin_template': ['http://192.168.41.10:8774/v2/%(project_id)s'],
                          'nova_endpoint_template': ['http://192.168.41.10:8774/v2/%(project_id)s'],
                          'os_region_name': ['RegionOne'],
                          'osapi_volume_listen': ['192.168.41.1'],
                          'osapi_volume_workers': ['12'],
                          'quota_backup_gigabytes': ['-1'],
                          'quota_backups': ['-1'],
                          'quota_snapshots': ['-1'],
                          'rpc_response_timeout': ['60'],
                          'storage_availability_zone': ['zettakit'],
                          'use_stderr': ['false'],
                          'verbose': ['true'],
                          'volume_clear': ['none'],
                          'volume_driver': ['cinder.volume.drivers.rbd.RBDDriver'],
                          'volume_service_inithost_offload': ['true']},
              'database': {'connection': ['mysql+pymysql://cinder:cinder_dbpass@192.168.41.10/cinder'],
                           'db_max_retries': ['-1'],
                           'db_max_retry_interval': ['1'],
                           'max_retries': ['-1'],
                           'retry_interval': ['1'],
                           'use_db_reconnect': ['true']},
              'keystone_authtoken': {'auth_type': ['password'],
                                     'auth_uri': ['http://192.168.41.10:5000'],
                                     'auth_url': ['http://192.168.41.10:35357'],
                                     'auth_version': ['v3'],
                                     'password': ['cinder'],
                                     'project_domain_name': ['default'],
                                     'project_name': ['service'],
                                     'region_name': ['RegionOne'],
                                     'user_domain_name': ['default'],
                                     'username': ['cinder']},
              'normal': {'max_over_subscription_ratio': ['10'],
                         'rados_connect_timeout': ['5'],
                         'rados_connection_interval': ['5'],
                         'rados_connection_retries': ['3'],
                         'rbd_ceph_conf': ['/etc/ceph/ceph.conf'],
                         'rbd_cluster_name': ['ceph'],
                         'rbd_exclusive_cinder_pool': ['false'],
                         'rbd_flatten_volume_from_snapshot': ['false'],
                         'rbd_max_clone_depth': ['5'],
                         'rbd_pool': ['volumes'],
                         'rbd_secret_uuid': ['7e0fb456-26bd-4b14-b039-2b986fdcbcc4'],
                         'rbd_store_chunk_size': ['4'],
                         'rbd_user': ['openstack'],
                         'volume_backend_name': ['normal'],
                         'volume_driver': ['cinder.volume.drivers.rbd.RBDDriver']},
              'oslo_concurrency': {'lock_path': ['$state_path/tmp']},
              'oslo_messaging_rabbit': {'amqp_durable_queues': ['false'],
                                        'heartbeat_rate': ['2'],
                                        'heartbeat_timeout_threshold': ['30'],
                                        'kombu_failover_strategy': ['round-robin'],
                                        'rabbit_ha_queues': ['true'],
                                        'rabbit_hosts': ['192.168.41.1:5672, 192.168.41.2:5672, 192.168.41.3:5672'],
                                        'rabbit_max_retries': ['0'],
                                        'rabbit_password': ['openstack'],
                                        'rabbit_retry_backoff': ['2'],
                                        'rabbit_retry_interval': ['1'],
                                        'rabbit_userid': ['openstack']},
              'resource': {'auth_uri': ['http://192.168.41.10:5000/v3'],
                           'password': ['cinder'],
                           'project_domain_name': ['default'],
                           'project_name': ['service'],
                           'user_domain_name': ['default'],
                           'username': ['cinder']}},
             {'DEFAULT': {'auth_strategy': ['keystone'],
                          'iscsi_helper': ['lioadm'],
                          'lock_path': ['/var/lib/cinder/tmp'],
                          'logdir': ['/var/log/cinder'],
                          'rootwrap_config': ['/etc/cinder/rootwrap.conf'],
                          'state_path': ['/var/lib/cinder'],
                          'volumes_dir': ['/etc/cinder/volumes']},
              'database': {'connection': ['mysql://cinder:cinder@localhost/cinder']},
              'keystone_authtoken': {'auth_host': ['127.0.0.1'],
                                     'auth_port': ['35357'],
                                     'auth_protocol': ['http']}}],
 'backend_host': None,
 'config_dir': None,
 'config_file': ['/usr/share/cinder/cinder-dist.conf',
                 '/etc/cinder/cinder.conf'],
 'debug': 'false',
 'log_config_append': None,
 'log_date_format': None,
 'log_dir': '/var/log/cinder',
 'log_file': '/var/log/cinder/volume.log',
 'state_path': '/var/lib/cinder',
 'syslog_log_facility': None,
 'use_syslog': None,
 'verbose': 'true',
 'watch_log_file': None}